version: '3'

services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}
    volumes:
      - .:/home/node/app

  psql-db:
    image: postgres:15.4-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      PGTZ: UTC
      TZ: UTC
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:5.0.7-alpine

volumes:
  psql-data: